Name:           ros-indigo-denso-robot-descriptions
Version:        3.0.2
Release:        1%{?dist}
Summary:        ROS denso_robot_descriptions package

Group:          Development/Libraries
License:        MIT
URL:            http://ros.org/wiki/denso_robot_descriptions
Source0:        %{name}-%{version}.tar.gz

BuildRequires:  ros-indigo-catkin

%description
The denso robot descriptions package includes URDF files for DENSO robots.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Sun Dec 24 2017 DENSO WAVE INCORPORATED <denso_robot_soft@denso-wave.co.jp> - 3.0.2-1
- Autogenerated by Bloom

* Sun Dec 17 2017 DENSO WAVE INCORPORATED <denso_robot_soft@denso-wave.co.jp> - 3.0.2-0
- Autogenerated by Bloom

* Thu Dec 07 2017 DENSO WAVE INCORPORATED <denso_robot_soft@denso-wave.co.jp> - 3.0.1-0
- Autogenerated by Bloom

