Name:           ros-indigo-denso-robot-control
Version:        3.0.2
Release:        0%{?dist}
Summary:        ROS denso_robot_control package

Group:          Development/Libraries
License:        MIT
URL:            http://ros.org/wiki/denso_robot_control
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-indigo-bcap-core
Requires:       ros-indigo-bcap-service
Requires:       ros-indigo-controller-manager
Requires:       ros-indigo-denso-robot-core
Requires:       ros-indigo-hardware-interface
Requires:       ros-indigo-joint-limits-interface
Requires:       ros-indigo-roscpp
Requires:       ros-indigo-std-msgs
Requires:       ros-indigo-transmission-interface
BuildRequires:  ros-indigo-bcap-core
BuildRequires:  ros-indigo-bcap-service
BuildRequires:  ros-indigo-catkin
BuildRequires:  ros-indigo-controller-manager
BuildRequires:  ros-indigo-denso-robot-core
BuildRequires:  ros-indigo-hardware-interface
BuildRequires:  ros-indigo-joint-limits-interface
BuildRequires:  ros-indigo-roscpp
BuildRequires:  ros-indigo-std-msgs
BuildRequires:  ros-indigo-transmission-interface

%description
The denso robot control package includes a node for controlling DENSO robot
controllers with MoveIt!.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Sun Dec 17 2017 DENSO WAVE INCORPORATED <denso_robot_soft@denso-wave.co.jp> - 3.0.2-0
- Autogenerated by Bloom

* Thu Dec 07 2017 DENSO WAVE INCORPORATED <denso_robot_soft@denso-wave.co.jp> - 3.0.1-0
- Autogenerated by Bloom

